### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by ivanprado** [cr0hn/aiohttp-cache#17]
Hi, I was trying to use this library but I noticed that version `1.1.0` was not published in pip. Consider publishing it :+1:

**Comment by ZhukovGreen** [comment]
Hi @ivanprado, why don’t you use the latest 2.0.1 version?

**Comment by ivanprado** [comment]
Hi @ZhukovGreen. I tried:
```
pip install aiohttp-cache==2.0.1
ERROR: Could not find a version that satisfies the requirement aiohttp-cache==2.0.1 (from versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for aiohttp-cache==2.0.1
```
Am I doing something wrong?

**Comment by ZhukovGreen** [comment]
I tested it in a clean container `python:3.8` and it works. I think I know what wrong here.
The library supports only the latest python version, which is 3.8. I plan to make it compatible with other python versions, but this is not done yet.
I guess version 2.0.0 should also work for python 3.6 and 3.7

**Comment by ZhukovGreen** [comment]
ref #18

**Comment by ivanprado** [comment]
Ok, yes, that explains the case, I'm working with python 3.6. Thank you. 

Please, consider adding a place where the available releases can be seen. I didn't know that version 2.0.1 was the latest.

**Comment by ZhukovGreen** [comment]
@ivanprado the place is here https://pypi.org/project/aiohttp-cache/ . You can always see the compatible release there.
Also you can list all available versions by typing:
`pip install aiohttp-cache==`
