### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by jirimichal** [cr0hn/aiohttp-cache#2]
When I run
`from aiohttp_cache import cache, setup_cache`
I get this error
`ImportError: No module named 'aiohttp.web_reqrep'`

Does the module aiohttp.web_reqrep exist?
PS: it is in file middleware.py

**Comment by darelvc** [comment]
I have same problem, maybe you have any answers about this?

**Comment by jersobh** [comment]
same problem here

**Comment by psiofxt** [comment]
@darelvc @jersobh It seems like the package is out of date on pypi so `pip install aiohttp-cache` will be out of date with the current version of `aiohttp`.

Doing `pip install git+https://github.com/cr0hn/aiohttp-cache.git` should solve your guys' issues.

**Comment by psiofxt** [comment]
@jersobh Try `pip uninstall aiohttp-cache` first. Then install from git.
