### ISSUE TITLE
Bug when using custom middlewares

### ISSUE THREAD

**Issue by Selutario** [cr0hn/aiohttp-cache#22]
Hello,

I found an unexpected behaviour under this circumstance. I detail it below.

## Description
When using aiohttp, if I add extra middlewares like in this example
```Python
app.add_api('spec.yaml',
            arguments={'title': 'Wazuh API',
                       'protocol': 'https' if configuration['https']['enabled'] else 'http',
                       'host': configuration['host'],
                       'port': configuration['port']
                       },
            strict_validation=True,
            validate_responses=True,
            pass_context_arg_name='request',
            options={"middlewares": [set_user_name, check_experimental(experimental)]})
```
aiohttp_cache stop working correctly. It is important to note that some useful libraries like [connexion](https://github.com/zalando/connexion)  adds its own middlewares, so maybe it is important so consider a fix for this.

I think I was able to discover the origin of the problem. The handler generated when calling the function decorated with `@cache` is itself wrapped by other handlers created in each extra middlewares. Below is an example image:
![imageedit_2_8012954543](https://user-images.githubusercontent.com/23361101/78794407-fda86580-79b3-11ea-88f1-d9173f400f05.png)

## Fix
It would be necessary to look for these attributes recursively or to devise a different way in which to control the cache variables. Something like this works in my tests, although it is only a suggestion and I have not been able to dedicate much time to it.

```Python
def get_original_handler(handler):
    if hasattr(handler, 'cache_enable'):
        return handler
    elif hasattr(handler, 'keywords'):
        return get_original_handler(handler.keywords['handler'])


@web.middleware
async def cache_middleware(request, handler):

    original_handler = get_original_handler(handler)

    if getattr(original_handler, "cache_enable", False):
        ...
```

I hope you find this useful.

Kind regards,
Selu.

**Comment by ZhukovGreen** [comment]
@Selutario btw should be available in 2.0.2 version (will be uploaded to pypi in a moment) https://gitlab.com/zhukovgreen/aiohttp-cache/pipelines/134127294
