### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by bbartling** [cr0hn/aiohttp-cache#40]
Hi 

I apologize for putting in a git issue, but curious if this is possible.

Could I ever POST JSON data to an aiohttp route, and then "cache" the JSON data to be used on a seperate GET route? 

Hopefully this makes sense, I apologize I am still learning.. Like for example I am experimenting with POSTing a "user name", can this same "user name" be retrieved on the GET route?

```
from aiohttp import web


async def handle(request):
    response_obj = { 'status' : 'success' }

    # USE CACHED VALUE?
    return web.json_response(response_obj)


async def new_user(request):
    try:
        user = await request.json()
        print(user['name'])
        info = f"Creating new user with name: {user['name']}"
        print(info)

        # CAN I CACHE THIS response_obj?
        response_obj = { 'status' : 'success', 'info': info}
        return web.json_response(response_obj, status=200)
    except Exception as e:
        response_obj = { 'status' : 'failed', 'reason': str(e) }
        return web.json_response(response_obj, status=500)


app = web.Application()
app.router.add_get('/', handle)
app.router.add_post('/user', new_user)

web.run_app(app)
```

**Comment by ZhukovGreen** [comment]
Hey @bbartling sorry for not replying for a while. I'll look into it asap

**Comment by ZhukovGreen** [comment]
Basically not:
Aiohttp cache has the following principle:

If the handler is marked as to be cached (@cache decorator), then requests to THIS handler will be stored in the caching backed with the key 

DEFAULT_KEY_PATTERN = (
    AvailableKeys.method,
    AvailableKeys.host,
    AvailableKeys.path,
    AvailableKeys.postdata,
    AvailableKeys.ctype,
)

And value equals to the response.

This is it

**Comment by bbartling** [comment]
Thanks for the response!
