### ISSUE TITLE
backend_config option is missing in the documentation

### ISSUE THREAD

**Issue by xingshou** [cr0hn/aiohttp-cache#6]
In the Custom Bandend / Redis, the following example code is shown.

As is:

redis_config = RedisConfig(db=4,
                           key_prefix="my_example")
setup_cache(app, cache_type="redis")

To be:

redis_config = RedisConfig(db=4,
                           key_prefix="my_example")
setup_cache(app, cache_type="redis", backend_config=redis_config)

I think backend_config option is missing in calling setup_cache, though it might set-up with the default option without error.

Sungsoo Kim

**Comment by ZhukovGreen** [comment]
No longer valid after merged #14
